# Generated by Django 2.2.16 on 2020-09-24 12:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='工具版本')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.Tool')),
            ],
        ),
    ]
