# Generated by Django 2.2.16 on 2020-09-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tool.Tool')),
            ],
        ),
    ]
