# Generated by Django 2.2.16 on 2020-09-24 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='工具名')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
            },
        ),
    ]
